version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: aleksey2299/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    image: aleksey2299/taski_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: aleksey2299/taski_gateway
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/